apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gsaepzs71-dotnet-basic
  janus-idp.io/tekton: gsaepzs71-dotnet-basic
  backstage.io/kubernetes-id: gsaepzs71-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gsaepzs71-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
